grp/urls.py
from django.urls import path
from . import views
from .views import (
	PostDetailView,
	PostCreateView,
	PostUpdateView,
	PostDeleteView
)

urlpatterns = [
    path('home/<name>/', views.Grphome, name='grouphome'),
    path('profile/<name>/',views.ShowProfile, name='userprofile'),
    path('sendmessage/',views.SendMessage, name = 'sendMessage'),
	path('checkmessages/',views.LoadMessages, name='checkMessages'),
	path('sendRequest/',views.sendRequest, name='sendRequest'),
	path('cancelRequest/',views.cancelRequest, name='cancelRequest'),
	path('acceptRequest/',views.acceptRequest, name='acceptRequest'),
	path('removeFriend/',views.removeFriend, name='removeFriend'),
	path('reportUser/',views.reportUser, name='reportUser'),
	path('rejectRequest/',views.rejectRequest, name='rejectRequest'),
	path('fetchNotifs/',views.fetchNotifs, name='fetchNotifs'),
	path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
	path('post/new', PostCreateView.as_view(), name='post-create'),
	path('post/<int:pk>/update', PostUpdateView.as_view(), name='post-update'),
	path('post/<int:pk>/delete', PostDeleteView.as_view(), name='post-delete'),
	path('post/<int:pk>/comment', views.add_comment, name='post-comment')
]

main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('grp.urls'))
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from . import views
from .views import GroupCreateView
urlpatterns = [
    path('', views.home, name = 'homepage'),
     path('about/', views.about, name = 'about'),
    path('register/', views.UserRegister, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('home/',views.Homeacc, name = 'user-home'),
    path('sent/', views.activation_sent_view, name="activation_sent"),
    path('activate/<slug:uidb64>/<slug:token>/', views.activate, name='activate'),
    path('updateProfile/',views.updateProfile, name='updateProfile'),
    path('group/new', GroupCreateView.as_view(), name='group-create'),
    path('password-reset/', 
    auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', 
    auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', 
    auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', 
    auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('profile/delete/confirmation/', views.deleteprofile, name='profile-delete-conf'),
    path('profile/delete/', views.deleteprof, name = 'profile-delete')

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from django.utils import timezone
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth import login, authenticate
# Create your models here.
GROUP =[
    ('TECAPP', 'Tech: App development'),
    ('TECCP', 'Tech: Competitive Programming'),
    ('TECAI', 'Tech: Artificial Intelligence'),
    ('TECDS', 'Tech: Data Science'),
    ('CPEUPSC', 'Competitive exams: UPSC'),
    ('CPECAT', 'Competitive exams: CAT'),
    ('CPEGRE', 'Competitive exams: GRE'),
    ('CPEGATE', 'Competitive exams: GATE'),
    ('SPFGYM', 'Sports and Fitness: Gym'),
    ('SPFFB', 'Sports and Fitness: Football'),
    ('ARTSKE', 'Arts and Crafts: Sketching'),
    ('ARTDA', 'Arts and Crafts: Digital Arts'),
    ('MAMMI', 'Music and Movies: Musical Instruments'),
    ('MAMFM', 'Music and Movies: Film making'),
]
GROUPS = [('','---------')] + GROUP
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    group = models.CharField(max_length=100, choices=GROUPS)
    email = models.EmailField(max_length=150)
    image = models.ImageField(default='default.JPG', upload_to='profile_pics')
    friends	= models.ManyToManyField("self")
    notif_count	= models.PositiveSmallIntegerField(default=0)
    institute = models.CharField(max_length = 200, default='')
    signup_confirmation = models.BooleanField(default=False)
    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300,300)
            img.thumbnail(output_size)
            img.save(self.image.path)


@receiver(post_save, sender=User)
def update_profile_signal(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()


class Groupf(models.Model):
    group_name = models.CharField(max_length = 100,choices = GROUPS)
    users = models.ManyToManyField(Profile)

    def __str__(self):
        return self.group_name

class group_new(models.Model):
    groupname = models.CharField(max_length = 100, default='')

    def __str__(self):
        return self.groupname

users/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile
GROUP =[
    ('TECAPP', 'Tech: App development'),
    ('TECCP', 'Tech: Competitive Programming'),
    ('TECAI', 'Tech: Artificial Intelligence'),
    ('TECDS', 'Tech: Data Science'),
    ('CPEUPSC', 'Competitive exams: UPSC'),
    ('CPECAT', 'Competitive exams: CAT'),
    ('CPEGRE', 'Competitive exams: GRE'),
    ('CPEGATE', 'Competitive exams: GATE'),
    ('SPFGYM', 'Sports and Fitness: Gym'),
    ('SPFFB', 'Sports and Fitness: Football'),
    ('ARTSKE', 'Arts and Crafts: Sketching'),
    ('ARTDA', 'Arts and Crafts: Digital Arts'),
    ('MAMMI', 'Music and Movies: Musical Instruments'),
    ('MAMFM', 'Music and Movies: Film making'),
]
GROUPS = [('','---------')] + GROUP
class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=150, required=True)
    group = forms.ChoiceField(choices=GROUPS, required=True)
    institute = forms.CharField(max_length=200, required=True)
    class Meta:
        model =  User
        fields = ('username', 'email', 'password1', 'password2', 'group', 'institute',)

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']
    
class ProfileUpdateForm(forms.ModelForm):
	class Meta:
		model = Profile
		fields = ['group', 'image', 'institute']

users/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from django.http import HttpResponse, JsonResponse
from .models import Profile, Groupf, group_new
from .forms import UserRegistrationForm, ProfileUpdateForm, UserUpdateForm
from django.contrib.auth.forms import User
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.utils.http import urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from .tokens import account_activation_token
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_text
from django.core.mail import EmailMessage
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import CreateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

def home(request):
    return render(request, 'users/homepage.html')

def about(request):
    return render(request, 'users/about.html')

def activation_sent_view(request):
    return render(request, 'users/activation_sent.html')


def UserRegister(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()
            user.profile.email = form.cleaned_data.get('email')
            user.profile.group = form.cleaned_data.get('group')
            user.profile.institute = form.cleaned_data.get('institute')
            # user.save()
            # username = form.cleaned_data.get('username')
            # password = form.cleaned_data.get('password1')
            # user = authenticate(username=username, password=password)
            # login(request, user)
            # r_user = User.objects.filter(username = username).first()
            # r_pro = Profile.objects.filter(user = r_user).first()
            # r_group = Groupf.objects.filter(group_name = r_pro.group).first()
            # r_group.users.add(r_pro)
            # messages.success(request,"Account Created for %s is created. Login!" %username)
            # return redirect('login') 
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            subject = 'Please Activate Your Account'
            message = render_to_string('users/activation_request.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                # method will generate a hash value with user related data
                'token': account_activation_token.make_token(user),
            })
            to_email = user.profile.email
            email_user = EmailMessage(subject, message, to=[to_email])
            email_user.send()
            return redirect('activation_sent')
    else:
        form = UserRegistrationForm()
    return render(request, 'users/register.html', {'form': form}) 

def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    # checking if the user exists, if the token is valid.
    if user is not None and account_activation_token.check_token(user, token):
        # if valid set active true 
        user.is_active = True
        # set signup_confirmation true
        user.profile.signup_confirmation = True
        user.save()
        username = user.username
        r_user = User.objects.filter(username = username).first()
        r_pro = Profile.objects.filter(user = r_user).first()
        r_pro.notif_count = 0
        r_group = Groupf.objects.filter(group_name = r_pro.group).first()
        r_group.users.add(r_pro)
        messages.success(request,"Account Created for %s is created. Login!" %username)
        return redirect('login')
    else:
        return render(request, 'users/activation_invalid.html')

def Homeacc(request):
    groups = Groupf.objects.all() 
    return render(request, 'users/acchome.html', {'groups':groups})
    
@login_required
def updateProfile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            group = p_form.cleaned_data.get('group')
            r_group = Groupf.objects.filter(group_name = group).first()
            r_pro = Profile.objects.filter(user = request.user).first()
            r_group.users.add(r_pro)
            messages.success(request, f'Your account has been updated')
            return redirect('login')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)
        
    context = {
        'u_form': u_form,
        'p_form': p_form,
     }
    return render(request, 'users/updatepro.html', context)

class GroupCreateView(SuccessMessageMixin, CreateView):
    model= group_new
    fields = ['groupname']
    success_url = '/home'
    success_message = "Group will be created! After a while, go to profile and update your group"

    def form_valid(self, form):
        return super().form_valid(form)

# class ProfileDelete(LoginRequiredMixin, DeleteView):
#     model = Profile
#     def get_success_url(self):
#         profile = self.get_object()
#         return reverse_lazy('homepage')


def deleteprofile(request):
    profile = Profile.objects.filter(user = request.user).first()
    user = User.objects.filter(username = request.user.username).first()
    #profile.delete()
    #messages.success(request, "Your profile is deleted") 
    return render(request, 'users/profiledelete.html')
def deleteprof(request):
    profile = Profile.objects.filter(user = request.user).first()
    user = User.objects.filter(username = request.user.username).first()
    profile.delete()
    user.delete()
    messages.success(request, "Your profile is deleted, Logout before proceeding")
    return render(request, 'users/delete.html') 

users/templates/users/acchome.html
{% extends "users/base2.html" %}
{% block content %}
  <p>Select the group you have entered during registration</p>
  {% for group in groups %}
    <article class="media content-section">
        <h2><a href="{% url 'grouphome' group.group_name %}">{{group.get_group_name_display}}</a></h2>
    </article>
  {% endfor %}
  <a href="{%url 'group-create' %}"><button class='btn btn-primary mx-1 '> <strong>+</strong> Create Group </button></a>
{% endblock content %}

<!-- <article class="media content-section">
    <div class="media-body">
      <h2><a href="{% url 'grouphome' grp.pk %}">App Development</a></h2>
    </div>
  </article>
  <article class="media content-section">
    <div class="media-body">
      <h2>Web Development</h2>
      <p class="article-content">Web Development section</p>
      <div class="container">
        <button type="button" class="btn btn-success">Join Group</button>
      </div>
    </div>
  </article>
  <article class="media content-section">
    <div class="media-body">
      <h2>Competitive Programming</h2>
      <p class="article-content">Competitive Programming section</p>
      <div class="container">
        <button type="button" class="btn btn-success">Join Group</button>
      </div>
    </div>
  </article>

  <article class="media content-section">
    <div class="media-body">
      <h2>Machine Learning</h2>
      <p class="article-content">Machine Learning section</p>
      <div class="container">
        <button type="button" class="btn btn-success">Join Group</button>
      </div>
    </div>
  </article>
  <article class="media content-section">
    <div class="media-body">
      <h2>Deep Learning</h2>
      <p class="article-content">Deep Learning section</p>
      <div class="container">
        <button type="button" class="btn btn-success">Join Group</button>
      </div>
    </div>
  </article>
  <article class="media content-section">
    <div class="media-body">
      <h2>Neural Networks</h2>
      <p class="article-content">Neural Networks section</p>
      <div class="container">
        <button type="button" class="btn btn-success">Join Group</button>
      </div>
    </div>
  </article> -->

users/templates/users/activation_invalid.html
{% extends "users/base2.html" %}
{% block content %}
    <div class = "alert alert-info">
        Activation link is invalid.
    </div>
{% endblock content %}

users/templates/users/activation_request.html
{% autoescape off %}
Hi {{ user.username }},

Please click the following link to confirm your registration:

http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

users/templates/users/activation_sent.html
{% extends "users/base2.html" %}
{% block content %}
    <div class = "alert alert-info">
        Activation link sent! Please check your email.
    </div>
{% endblock content %}

users/templates/users/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    

    <link rel="stylesheet" type="text/css" href="{% static 'users/main.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    {% if title %}
        <title>Work Together - {{ title }}</title>
    {% else %}
        <title>Work Together</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark" style="background-color:  #2a6679;" >
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'homepage' %}">Work Together</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              {% if user.is_authenticated %}
              <a class="nav-item nav-link" href="{% url 'user-home' %}">Home</a>
              {% else %}
              <a class="nav-item nav-link" href="{% url 'homepage' %}">Home</a>
              {% endif %}
              <a class="nav-item nav-link" href="{% url 'about' %}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if user.is_authenticated %}
                <a class="btn btn-info mx-1 my-1" href="{% url 'updateProfile' %}">Profile</a>
                  <a class="btn btn-info mx-1 my-1" data-toggle="modal" id='notif_btn' data-target="#notifModal"> Notifications <span class="badge badge-light" id="notif_count_span">{{user.notif_count}}</span> </a>
                  <!-- The Modal -->
              <div class="modal" id="notifModal">
                <div class="modal-dialog modal-dialog-scrollable">
                  <div class="modal-content">
                  
                    <!-- Modal Header -->
                    <div class="modal-header">
                      <h1 class="modal-title">Notifications</h1>
                      <button type="button" class="close" data-dismiss="modal">×</button>
                    </div>
                    
                    <!-- Modal body -->
                    <div class="modal-body" id='notif_body'>
                      <h3>No Notifications</h3>
                      
                    </div>
                    
                    <!-- Modal footer -->
                    <div class="modal-footer">
                      <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                    </div>
                    
                  </div>
                </div>
              </div>
                <a class="btn btn-info mx-1 my-1" href="{% url 'logout' %}">Logout</a>
              {% else %}
                <a class="btn btn-info mx-1 my-1" href="{% url 'login' %}">Login</a>
                <a class="btn btn-info mx-1 my-1" href="{% url 'register' %}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <div class="container-fluid">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
                </div>
            {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
        </div>
</body>

<script type="text/javascript">
  $('#notif_btn').click(function()                     //collecting notifs
    {
        $.ajax(
        {
          type:'GET',
          url :"{% url 'fetchNotifs' %}",
          data:{
                  
          },
          success: function( data )
          {
            var gata =JSON.stringify(data);
            var bata =JSON.parse(gata);
            if (bata.status == "notifs found")
            {
              var str = "";
              for (var i=0;i<bata.contents.length;i++)
                str += "<b>"+bata.generators[i]+"</b> "+bata.contents[i]+"<br>";
              $('#notif_body').html(str);
              $('#notif_count_span').html('0')
            }
            else  
              $('#notif_body').html("You're all caught up!");
          },
          error:function (xhr, ajaxOptions, thrownError)
          {
            alert(xhr.status);
            alert(xhr.statusText);
            alert(xhr.responseText);
          } 
        })
    });
</script>

</html>

users/templates/users/base2.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    

    <link rel="stylesheet" type="text/css" href="{% static 'users/main.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    {% if title %}
        <title>Work Together - {{ title }}</title>
    {% else %}
        <title>Work Together</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark" style="background-color:  #2a6679;" >
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'homepage' %}">Work Together</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              {% if user.is_authenticated %}
              <a class="nav-item nav-link" href="{% url 'user-home' %}">Home</a>
              {% else %}
              <a class="nav-item nav-link" href="{% url 'homepage' %}">Home</a>
              {% endif %}
              <a class="nav-item nav-link" href="{% url 'about' %}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if user.is_authenticated %}
                <a class="btn btn-info mx-1 my-1" href="{% url 'updateProfile' %}">Profile</a>
                  <a class="btn btn-info mx-1 my-1" data-toggle="modal" id='notif_btn' data-target="#notifModal"> Notifications <span class="badge badge-light" id="notif_count_span">{{user.notif_count}}</span> </a>
                  <!-- The Modal -->
              <div class="modal" id="notifModal">
                <div class="modal-dialog modal-dialog-scrollable">
                  <div class="modal-content">
                  
                    <!-- Modal Header -->
                    <div class="modal-header">
                      <h1 class="modal-title">Notifications</h1>
                      <button type="button" class="close" data-dismiss="modal">×</button>
                    </div>
                    
                    <!-- Modal body -->
                    <div class="modal-body" id='notif_body'>
                      <h3>No Notifications</h3>
                      
                    </div>
                    
                    <!-- Modal footer -->
                    <div class="modal-footer">
                      <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                    </div>
                    
                  </div>
                </div>
              </div>
                <a class="btn btn-info mx-1 my-1" href="{% url 'logout' %}">Logout</a>
              {% else %}
                <a class="btn btn-info mx-1 my-1" href="{% url 'login' %}">Login</a>
                <a class="btn btn-info mx-1 my-1" href="{% url 'register' %}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <div class="container">
      <div class="row">
         <div class="col-md-8">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
        </div>
      </div>
    </div>
        <!-- <div class="col-md-4">
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Latest Posts</li>
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Calendars</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>
          </div>
        </div> -->


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
   
</body>

<script type="text/javascript">
  $('#notif_btn').click(function()                     //collecting notifs
    {
        $.ajax(
        {
          type:'GET',
          url :"{% url 'fetchNotifs' %}",
          data:{
                  
          },
          success: function( data )
          {
            var gata =JSON.stringify(data);
            var bata =JSON.parse(gata);
            if (bata.status == "notifs found")
            {
              var str = "";
              for (var i=0;i<bata.contents.length;i++)
                str += "<b>"+bata.generators[i]+"</b> "+bata.contents[i]+"<br>";
              $('#notif_body').html(str);
              $('#notif_count_span').html('0')
            }
            else  
              $('#notif_body').html("You're all caught up!");
          },
          error:function (xhr, ajaxOptions, thrownError)
          {
            alert(xhr.status);
            alert(xhr.statusText);
            alert(xhr.responseText);
          } 
        })
    });
</script>
</html>

users/templates/users/delete.html
{% extends "users/base2.html" %}
{% block content %}
    <div class="content-section">
            <h3>Your account is deleted, Logout before proceeding</h3>
    </div>
{% endblock content %}

users/templates/users/group_new_form.html
{% extends "users/base2.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Create Group</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="from-group">
                <button class="btn btn-outline-info" type="Submit">Create</button>
            </div>
        </form>
    </div>
{% endblock content %}

users/templates/users/login.html
{% extends "users/base2.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="from-group">
                <button class="btn-outline-info" type="submit">Login</button>
                <small class="test-muted ml=2">
                    <a href="{% url 'password_reset' %}">Forgot Password</a>
                </small>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need an account? <a class"ml-2" href="{% url 'register' %}">Sign up now</a>
            </small>
        </div>
    </div>
{% endblock content %}

users/templates/users/logout.html
{% extends "users/base2.html" %}
{% block content %}
    <h2>You have been logged out</h2>
    <div class="content-section">
        <div class="border-top pt-3">
            <small class="text-muted">
                <a href="{% url 'login' %}"">Login again</a>
            </small>
        </div>
    </div>
{% endblock content %}

users/templates/users/password_reset.html
{% extends "users/base2.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="from-group">
                <button class="btn-outline-info" type="submit">Request Password Reset</button>
            </div>
        </form>
    </div>
{% endblock content %}

users/templates/users/password_reset_confirm.html
{% extends "users/base2.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="from-group">
                <button class="btn-outline-info" type="submit">Request Password</button>
            </div>
        </form>
    </div>
{% endblock content %}

users/templates/users/register.html
{% extends "users/base2.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class='container border p-3'>
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="from-group">
                <button class="btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already Have An Account? <a class"ml-2" href="#">Sign in</a>
            </small>
        </div>
    </div>
{% endblock content %}